
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000048); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#anjel, #najzákladnejšie' WHERE uf_handle_id_ref = 11000048;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000070); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#anjel, #pobožnosť' WHERE uf_handle_id_ref = 11000070;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000044); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#anjel' WHERE uf_handle_id_ref = 11000044;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000043); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#anjel' WHERE uf_handle_id_ref = 11000043;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000219); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#anjel' WHERE uf_handle_id_ref = 11000219;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000098); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Božské Srdce, #zasvätenie, #Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000098;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000050); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Božské Srdce, #Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000050;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000097); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Božské Srdce, #Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000097;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000113); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Božské Srdce, #Kristus Ježiš' WHERE uf_handle_id_ref = 11000113;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000099); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci, #rodina, #k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000099;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000213); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci, #pobožnosť, #milosrdenstvo' WHERE uf_handle_id_ref = 11000213;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000254); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci, #milosrdenstvo' WHERE uf_handle_id_ref = 11000254;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000090); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci, #milosrdenstvo' WHERE uf_handle_id_ref = 11000090;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000089); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000089;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000255); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000255;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000205); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000205;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000092); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000092;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000138); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000138;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000139); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000139;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000252); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000252;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000253); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000253;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000187); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000187;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000091); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chorí umierajúci' WHERE uf_handle_id_ref = 11000091;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000046); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chválospev' WHERE uf_handle_id_ref = 11000046;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000082); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#chválospev' WHERE uf_handle_id_ref = 11000082;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000030); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#čnosti' WHERE uf_handle_id_ref = 11000030;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000021); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#čnosti' WHERE uf_handle_id_ref = 11000021;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000170); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#čnosti' WHERE uf_handle_id_ref = 11000170;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000133); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#čnosti' WHERE uf_handle_id_ref = 11000133;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000132); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#čnosti' WHERE uf_handle_id_ref = 11000132;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000120); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#čnosti' WHERE uf_handle_id_ref = 11000120;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000128); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#ďakovné' WHERE uf_handle_id_ref = 11000128;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000022); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #spoveď, #hriechy' WHERE uf_handle_id_ref = 11000022;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000056); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #chválospev' WHERE uf_handle_id_ref = 11000056;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000168); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #čnosti' WHERE uf_handle_id_ref = 11000168;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000086); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #ďakovné' WHERE uf_handle_id_ref = 11000086;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000248); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #mariánske' WHERE uf_handle_id_ref = 11000248;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000033); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #najzákladnejšie' WHERE uf_handle_id_ref = 11000033;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000179); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #pobožnosť' WHERE uf_handle_id_ref = 11000179;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000180); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý, #pobožnosť' WHERE uf_handle_id_ref = 11000180;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000028); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý' WHERE uf_handle_id_ref = 11000028;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000058); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý' WHERE uf_handle_id_ref = 11000058;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000250); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý' WHERE uf_handle_id_ref = 11000250;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000076); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý' WHERE uf_handle_id_ref = 11000076;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000017); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Duch Svätý' WHERE uf_handle_id_ref = 11000017;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000270); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000270;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000229); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000229;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000065); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000065;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000072); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätej žene' WHERE uf_handle_id_ref = 11000072;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000112); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätej žene' WHERE uf_handle_id_ref = 11000112;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000118); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätej žene' WHERE uf_handle_id_ref = 11000118;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000269); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #k svätej žene' WHERE uf_handle_id_ref = 11000269;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000271); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000271;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000227); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000227;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000222); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000222;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000198); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000198;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000211); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000211;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000228); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000228;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000235); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000235;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000069); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000069;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000221); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000221;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000226); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000226;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000223); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000223;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000217); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000217;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000233); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000233;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000272); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi' WHERE uf_handle_id_ref = 11000272;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000273); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi' WHERE uf_handle_id_ref = 11000273;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000111); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi' WHERE uf_handle_id_ref = 11000111;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000247); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi' WHERE uf_handle_id_ref = 11000247;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000218); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#k svätému mužovi' WHERE uf_handle_id_ref = 11000218;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000067); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000067;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000064); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000064;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000240); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000240;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000237); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000237;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000196); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Kristus Ježiš, #pobožnosť' WHERE uf_handle_id_ref = 11000196;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000161); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Kristus Ježiš' WHERE uf_handle_id_ref = 11000161;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000059); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000059;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000184); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000184;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000060); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000060;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000039); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000039;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000188); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000188;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000010); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000010;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000008); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000008;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000057); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#latinské' WHERE uf_handle_id_ref = 11000057;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000042); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #spoveď, #chválospev, #ďakovné' WHERE uf_handle_id_ref = 11000042;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000049); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #anjel, #najzákladnejšie' WHERE uf_handle_id_ref = 11000049;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000035); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #Veľkonočné obdobie, #najzákladnejšie' WHERE uf_handle_id_ref = 11000035;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000007); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #Pôstne obdobie, #pobožnosť' WHERE uf_handle_id_ref = 11000007;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000005); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #Veľkonočné obdobie, #pobožnosť' WHERE uf_handle_id_ref = 11000005;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000144); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #zasvätenie, #pobožnosť' WHERE uf_handle_id_ref = 11000144;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000038); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #najzákladnejšie' WHERE uf_handle_id_ref = 11000038;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000066); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000066;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000068); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000068;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000239); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000239;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000242); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000242;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000232); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000232;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000244); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000244;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000063); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000063;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000006); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000006;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000004); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000004;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000246); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #pobožnosť' WHERE uf_handle_id_ref = 11000246;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000123); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske, #zasvätenie' WHERE uf_handle_id_ref = 11000123;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000249); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske' WHERE uf_handle_id_ref = 11000249;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000208); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske' WHERE uf_handle_id_ref = 11000208;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000071); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske' WHERE uf_handle_id_ref = 11000071;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000207); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske' WHERE uf_handle_id_ref = 11000207;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000034); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mariánske' WHERE uf_handle_id_ref = 11000034;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000003); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo, #mariánske' WHERE uf_handle_id_ref = 11000003;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000200); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo, #pápež' WHERE uf_handle_id_ref = 11000200;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000236); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo, #pobožnosť' WHERE uf_handle_id_ref = 11000236;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000013); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo, #život z viery' WHERE uf_handle_id_ref = 11000013;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000012); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo, #život z viery' WHERE uf_handle_id_ref = 11000012;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000134); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000134;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000135); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000135;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000129); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000129;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000140); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000140;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000136); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000136;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000137); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000137;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000124); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000124;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000127); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#milosrdenstvo' WHERE uf_handle_id_ref = 11000127;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000245); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#misie, #k svätej žene' WHERE uf_handle_id_ref = 11000245;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000275); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#misie' WHERE uf_handle_id_ref = 11000275;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000263); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mládež, #k svätému mužovi' WHERE uf_handle_id_ref = 11000263;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000115); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mládež, #k svätému mužovi' WHERE uf_handle_id_ref = 11000115;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000150); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mládež' WHERE uf_handle_id_ref = 11000150;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000162); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mládež' WHERE uf_handle_id_ref = 11000162;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000155); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#mládež' WHERE uf_handle_id_ref = 11000155;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000231); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Najsvätejšia Trojica, #pobožnosť' WHERE uf_handle_id_ref = 11000231;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000147); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Najsvätejšia Trojica' WHERE uf_handle_id_ref = 11000147;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000047); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#najzákladnejšie' WHERE uf_handle_id_ref = 11000047;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000045); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#najzákladnejšie' WHERE uf_handle_id_ref = 11000045;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000020); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#najzákladnejšie' WHERE uf_handle_id_ref = 11000020;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000041); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#najzákladnejšie' WHERE uf_handle_id_ref = 11000041;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000040); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#najzákladnejšie' WHERE uf_handle_id_ref = 11000040;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000018); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#najzákladnejšie' WHERE uf_handle_id_ref = 11000018;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000083); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #prijímanie, #Pôstne obdobie, #Kristus Ježiš' WHERE uf_handle_id_ref = 11000083;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000146); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #prijímanie, #ďakovné' WHERE uf_handle_id_ref = 11000146;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000037); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #prijímanie, #ďakovné' WHERE uf_handle_id_ref = 11000037;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000116); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #Kristus Ježiš' WHERE uf_handle_id_ref = 11000116;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000036); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #prijímanie' WHERE uf_handle_id_ref = 11000036;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000176); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #zasvätení' WHERE uf_handle_id_ref = 11000176;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000175); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša, #zasvätení' WHERE uf_handle_id_ref = 11000175;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000191); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša' WHERE uf_handle_id_ref = 11000191;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000190); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša' WHERE uf_handle_id_ref = 11000190;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000189); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša' WHERE uf_handle_id_ref = 11000189;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000084); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša' WHERE uf_handle_id_ref = 11000084;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000081); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša' WHERE uf_handle_id_ref = 11000081;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000141); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#omša' WHERE uf_handle_id_ref = 11000141;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000182); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pápež, #k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000182;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000079); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pápež' WHERE uf_handle_id_ref = 11000079;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000080); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pápež' WHERE uf_handle_id_ref = 11000080;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000216); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pobožnosť' WHERE uf_handle_id_ref = 11000216;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000051); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pobožnosť' WHERE uf_handle_id_ref = 11000051;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000185); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pobožnosť' WHERE uf_handle_id_ref = 11000185;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000256); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#pobožnosť' WHERE uf_handle_id_ref = 11000256;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000148); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#povolanie' WHERE uf_handle_id_ref = 11000148;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000052); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#povolanie' WHERE uf_handle_id_ref = 11000052;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000114); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie, #rodina, #Vianočné obdobie' WHERE uf_handle_id_ref = 11000114;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000234); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie, #pobožnosť' WHERE uf_handle_id_ref = 11000234;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000166); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie, #rodina' WHERE uf_handle_id_ref = 11000166;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000167); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie, #rodina' WHERE uf_handle_id_ref = 11000167;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000171); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie, #rodina' WHERE uf_handle_id_ref = 11000171;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000031); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie' WHERE uf_handle_id_ref = 11000031;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000125); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#požehnanie' WHERE uf_handle_id_ref = 11000125;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000210); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#prijímanie' WHERE uf_handle_id_ref = 11000210;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000206); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#prijímanie' WHERE uf_handle_id_ref = 11000206;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000023); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#prikázania, #život z viery' WHERE uf_handle_id_ref = 11000023;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000053); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#prikázania, #život z viery' WHERE uf_handle_id_ref = 11000053;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000019); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#prikázania, #život z viery' WHERE uf_handle_id_ref = 11000019;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000054); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#prikázania, #život z viery' WHERE uf_handle_id_ref = 11000054;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000212); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #chorí umierajúci, #k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000212;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000197); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #k svätému mužovi, #k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000197;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000220); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #zasvätení, #mládež, #povolanie' WHERE uf_handle_id_ref = 11000220;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000152); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež, #povolanie' WHERE uf_handle_id_ref = 11000152;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000215); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #k svätému mužovi' WHERE uf_handle_id_ref = 11000215;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000096); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež' WHERE uf_handle_id_ref = 11000096;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000268); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež' WHERE uf_handle_id_ref = 11000268;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000156); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež' WHERE uf_handle_id_ref = 11000156;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000157); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež' WHERE uf_handle_id_ref = 11000157;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000158); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež' WHERE uf_handle_id_ref = 11000158;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000267); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #mládež' WHERE uf_handle_id_ref = 11000267;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000266); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #Vianočné obdobie' WHERE uf_handle_id_ref = 11000266;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000108); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina, #za rôzne potreby' WHERE uf_handle_id_ref = 11000108;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000194); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000194;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000195); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000195;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000230); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000230;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000085); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000085;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000151); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000151;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000153); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000153;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000154); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#rodina' WHERE uf_handle_id_ref = 11000154;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000009); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #chválospev, #ďakovné' WHERE uf_handle_id_ref = 11000009;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000027); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #prikázania, #život z viery' WHERE uf_handle_id_ref = 11000027;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000199); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #ďakovné' WHERE uf_handle_id_ref = 11000199;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000029); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #hriechy' WHERE uf_handle_id_ref = 11000029;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000026); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #hriechy' WHERE uf_handle_id_ref = 11000026;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000024); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #hriechy' WHERE uf_handle_id_ref = 11000024;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000016); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #hriechy' WHERE uf_handle_id_ref = 11000016;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000001); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #prikázania' WHERE uf_handle_id_ref = 11000001;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000172); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #vnútorné uzdravenie' WHERE uf_handle_id_ref = 11000172;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000178); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď, #zasvätení' WHERE uf_handle_id_ref = 11000178;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000002); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď' WHERE uf_handle_id_ref = 11000002;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000145); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď' WHERE uf_handle_id_ref = 11000145;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000088); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď' WHERE uf_handle_id_ref = 11000088;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000121); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď' WHERE uf_handle_id_ref = 11000121;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000122); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď' WHERE uf_handle_id_ref = 11000122;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000209); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#spoveď' WHERE uf_handle_id_ref = 11000209;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000078); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#stolovanie, #najzákladnejšie' WHERE uf_handle_id_ref = 11000078;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000077); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#stolovanie, #najzákladnejšie' WHERE uf_handle_id_ref = 11000077;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000011); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Sviatosť oltárna, #chválospev' WHERE uf_handle_id_ref = 11000011;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000201); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Sviatosť oltárna, #pobožnosť' WHERE uf_handle_id_ref = 11000201;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000087); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Sviatosť oltárna' WHERE uf_handle_id_ref = 11000087;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000241); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Sviatosť oltárna' WHERE uf_handle_id_ref = 11000241;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000126); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Sviatosť oltárna' WHERE uf_handle_id_ref = 11000126;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000259); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #mládež, #k svätej žene' WHERE uf_handle_id_ref = 11000259;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000261); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000261;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000225); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000225;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000224); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätému mužovi, #pobožnosť' WHERE uf_handle_id_ref = 11000224;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000264); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #zasvätení, #povolanie' WHERE uf_handle_id_ref = 11000264;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000274); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätej žene' WHERE uf_handle_id_ref = 11000274;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000238); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätému mužovi' WHERE uf_handle_id_ref = 11000238;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000117); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätému mužovi' WHERE uf_handle_id_ref = 11000117;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000262); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #k svätému mužovi' WHERE uf_handle_id_ref = 11000262;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000260); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska, #mládež' WHERE uf_handle_id_ref = 11000260;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000181); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska' WHERE uf_handle_id_ref = 11000181;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000276); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska' WHERE uf_handle_id_ref = 11000276;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000100); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska' WHERE uf_handle_id_ref = 11000100;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000257); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#územie Slovenska' WHERE uf_handle_id_ref = 11000257;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000183); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Veľkonočné obdobie, #chorí umierajúci, #k svätému mužovi, #k svätej žene, #pobožnosť' WHERE uf_handle_id_ref = 11000183;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000243); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#Vianočné obdobie' WHERE uf_handle_id_ref = 11000243;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000149); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#vnútorné uzdravenie' WHERE uf_handle_id_ref = 11000149;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000160); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#vnútorné uzdravenie' WHERE uf_handle_id_ref = 11000160;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000074); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#vnútorné uzdravenie' WHERE uf_handle_id_ref = 11000074;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000073); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#vnútorné uzdravenie' WHERE uf_handle_id_ref = 11000073;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000159); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#vnútorné uzdravenie' WHERE uf_handle_id_ref = 11000159;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000109); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby, #mládež, #povolanie, #čnosti' WHERE uf_handle_id_ref = 11000109;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000110); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby, #k svätému mužovi, #k svätej žene' WHERE uf_handle_id_ref = 11000110;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000186); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby, #mariánske' WHERE uf_handle_id_ref = 11000186;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000075); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000075;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000265); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000265;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000131); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000131;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000169); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000169;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000061); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000061;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000106); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000106;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000107); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000107;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000105); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000105;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000104); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000104;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000103); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000103;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000102); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000102;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000101); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#za rôzne potreby' WHERE uf_handle_id_ref = 11000101;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000062); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení, #pápež' WHERE uf_handle_id_ref = 11000062;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000095); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení, #povolanie' WHERE uf_handle_id_ref = 11000095;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000130); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení, #za rôzne potreby' WHERE uf_handle_id_ref = 11000130;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000204); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000204;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000177); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000177;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000094); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000094;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000163); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000163;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000093); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000093;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000119); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000119;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000164); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000164;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000165); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000165;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000192); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000192;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000258); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000258;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000202); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000202;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000203); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000203;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000193); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätení' WHERE uf_handle_id_ref = 11000193;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000143); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätenie, #pobožnosť' WHERE uf_handle_id_ref = 11000143;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000142); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zasvätenie' WHERE uf_handle_id_ref = 11000142;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000025); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#život z viery' WHERE uf_handle_id_ref = 11000025;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000174); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#život z viery' WHERE uf_handle_id_ref = 11000174;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000173); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#život z viery' WHERE uf_handle_id_ref = 11000173;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000055); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#život z viery' WHERE uf_handle_id_ref = 11000055;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000015); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#život z viery' WHERE uf_handle_id_ref = 11000015;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000014); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#život z viery' WHERE uf_handle_id_ref = 11000014;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000032); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zosnulí, #najzákladnejšie, #milosrdenstvo' WHERE uf_handle_id_ref = 11000032;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000214); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zosnulí, #pobožnosť, #milosrdenstvo' WHERE uf_handle_id_ref = 11000214;
INSERT OR IGNORE INTO user_flags (uf_handle_id_ref) VALUES (11000251); UPDATE user_flags SET uf_tag_list = IFNULL(uf_tag_list, '') || ', ' || '#zosnulí' WHERE uf_handle_id_ref = 11000251;

